/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import frames.MainMenu;
import javax.swing.ImageIcon;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author PC
 */
public class jpCreateEvent extends javax.swing.JPanel {

    private MainMenu mainMenu;
    /**
     * Creates new form jpCreateEvent
     */
    public jpCreateEvent(MainMenu mainM) {
        initComponents();
        
        this.mainMenu = mainM;
        
        Eventoselec();
    }
    
    private void Eventoselec(){
        String evntoselec = (String) cbxEvnt.getSelectedItem();

        ImageIcon bbshow = new ImageIcon(getClass().getResource("/images/baby-shower.png"));
        ImageIcon cumple = new ImageIcon(getClass().getResource("/images/happy-birthday.png"));
        ImageIcon quince = new ImageIcon(getClass().getResource("/images/quinceanera.png"));
        ImageIcon gradua = new ImageIcon(getClass().getResource("/images/graduacion.png"));
        ImageIcon wedding = new ImageIcon(getClass().getResource("/images/recien-casados.png"));
        ImageIcon convv = new ImageIcon(getClass().getResource("/images/copa-de-champan.png"));
        ImageIcon party = new ImageIcon(getClass().getResource("/images/cabina-de-dj.png"));
        
        if (evntoselec.equals("BabyShower")){
            jlTipoEvent.setIcon(bbshow);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        } else if (evntoselec.equals("Cumpleaños")){
            jlTipoEvent.setIcon(cumple);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        } else if (evntoselec.equals("Quinceaños")){
            jlTipoEvent.setIcon(quince);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        } else if (evntoselec.equals("Graduacion")){
            jlTipoEvent.setIcon(gradua);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        } else if (evntoselec.equals("Boda")){
            jlTipoEvent.setIcon(wedding);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        }else if (evntoselec.equals("Convivio")){
            jlTipoEvent.setIcon(convv);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        }else if (evntoselec.equals("Fiesta")){
            jlTipoEvent.setIcon(party);
            jlTipoEvent.setHorizontalAlignment(CENTER);
            jlTipoEvent.setVerticalAlignment(CENTER);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxEvnt = new models.CustomComboBox();
        jLabel3 = new javax.swing.JLabel();
        jlTipoEvent = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(762, 606));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CREA UN EVENTO");

        cbxEvnt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BabyShower", "Cumpleaños", "Quinceaños", "Graduacion", "Boda", "Convivio", "Fiesta" }));
        cbxEvnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEvntActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TIPO DE EVENTO");

        jlTipoEvent.setMaximumSize(new java.awt.Dimension(100, 100));
        jlTipoEvent.setMinimumSize(new java.awt.Dimension(100, 100));
        jlTipoEvent.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTipoEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxEvnt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEvnt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlTipoEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEvntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEvntActionPerformed
        Eventoselec();
    }//GEN-LAST:event_cbxEvntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private models.CustomComboBox cbxEvnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlTipoEvent;
    // End of variables declaration//GEN-END:variables
}
